service:
  symbols: KRW-BTC
  upbit:
    enabled: true
    ticket:
      ws: wss://api.upbit.com/websocket/v1
  bybit:
    enabled: false
    ticket:
      ws: wss://stream.bybit.com/v5/public/spot

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    io.cross.exchange: DEBUG
