spring:
  application:
    name: cross-exchange-bot

service:
  symbols: USDT-BTC, USDT-BCH, USDT-XRP, USDT-TRX, USDT-ETH, USDT-ETC, USDT-SC
  upbit:
    enabled: true
    order-book:
      ws: wss://api.upbit.com/websocket/v1
  bybit:
    enabled: false
    order-book:
      ping-interval: 30
      ws: wss://stream.bybit.com/v5/public/spot
  binance:
    enabled: false
    order-book:
      ws: wss://stream.binance.com:443

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    io.cross.exchange: INFO
