spring:
  application:
    name: cross-exchange-bot

service:
  symbols: USDT-BTC, USDT-BCH
  upbit:
    enabled: true
    order-book:
      ws: wss://api.upbit.com/websocket/v1
  bybit:
    enabled: true
    map:
      USDT-BTC: BTCUSDT
      USDT-BCH: BCHUSDT
    order-book:
      ping-interval: 30
      ws: wss://stream.bybit.com/v5/public/spot

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    io.cross.exchange: INFO
