spring:
  application:
    name: cross-exchange-bot

service:
  symbols: USDT-BTC, USDT-XRP, USDT-TRX, USDT-ETH, USDT-ETC
  upbit:
    enabled: true
    order-book:
      ws: wss://api.upbit.com/websocket/v1
  bybit:
    enabled: true
    order-book:
      ping-interval: 30
      ws: wss://stream.bybit.com/v5/public/spot
  binance:
    enabled: true
    order-book:
      timeout: 3
      ws: wss://stream.binance.com:443
  bitfinex:
    enabled: true
    order-book:
      ws: wss://api-pub.bitfinex.com/ws/2

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    loggers:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    io.cross.exchange: INFO
